import type { Metadata } from "next";
import "./globals.css";
import { AOSProvider } from "@/components/Aos/AOSProvider";
import Layout from "@/components/Layouts/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <AOSProvider>{children}</AOSProvider>
        </Layout>
      </body>
    </html>
  );
}
